name = "najd-api"
main = "worker/index.js"
compatibility_date = "2026-07-27"

[d1_databases]
binding = "DB"
database_name = "najd-db"
database_id = "fe3ec421-7b15-4ab3-b192-22ea5b30b86e"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
